Numpy


It is a multi dimensional array, can store all type to data in(1D ,2D, 3D)

List                                                             Numpy
->Slow:it stores all the values (Size, Object type etc).          ->Fast:It has fixed type(sotres value in int32).
->a = [1,2,3]
->b = [4,5,6] ->a*b = error                                      -> so it reads the values quickly.
                                                                 ->no type checking when iterating through object.
                                                                 ->Contiguous Memory allocation.
                                                                 ->a = np.array[1,2,3]
                                                                 ->b = np.array[4,5,6] -> a*b = np.array[4,10,18]
                                                                 Application -> 1.Mathematics
                                                                                2.Plotting(Matplotlib)
                                                                                3.Backend(Pandas, etc)
                                                                                4.ML

In [1]:
import numpy as np

Basics


In [2]:
a = np.array([1,2,3], dtype="int32")
print(a)

[1 2 3]


In [3]:
b = np.array([[1.0,2.0,3.0], [4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
#Get Dimension
b.ndim

2

In [5]:
#get Shape
b.shape


(2, 3)

In [6]:
#Get type
b.dtype

dtype('float64')

In [7]:
#Get Size
b.itemsize

8

In [8]:
#Get total size
a.nbytes

12

Acessing/chaning specific element,rows,coloumns,etc

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
a.shape

(2, 7)

In [11]:
#Get a specific element[r , c]
print(a[1,-2])

13


In [12]:
#Get specific Row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
#get specific coloumn
a[: ,3 ]

array([ 4, 11])

In [14]:
#Getting fancy [staringindex : endingindex : stepsize]
a[0 , 1:6:2]

array([2, 4, 6])

In [15]:
#Change
a[1,3] = 100
print(a)

a[: ,2] = 5
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10 100  12  13  14]]
[[  1   2   5   4   5   6   7]
 [  8   9   5 100  12  13  14]]


3 - D Example

In [44]:
A = np.array([[[1,2] , [3,4]], [[5,6] , [7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
#Get specific element(work outside in)
A[1, 1,0:1]

array([7])

In [32]:
#replace 
#A[1 , : , 0:2] = [[8 ,8], [9 ,9]]

In [35]:
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Initialize Different Types of Arrays

In [37]:
#All 0 : matrix
np.zeros((2,4 , 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [40]:
#All 1:matrix

np.ones((2,3,3) )

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
#Any other number

np.full((2,2) ,100 , dtype='float32')

array([[100., 100.],
       [100., 100.]], dtype=float32)

In [47]:
#Any other number(full_like)
#np.full(A.shape, 3)
np.full_like(A , 3)

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

In [50]:
#Random decimal numbers
np.random.rand(3,2,1)

array([[[0.97779793],
        [0.75048302]],

       [[0.56845543],
        [0.18918349]],

       [[0.29105166],
        [0.08450249]]])

In [51]:
np.random.random_sample(A.shape)

array([[[0.29987137, 0.67100211],
        [0.68984403, 0.1002857 ]],

       [[0.30192165, 0.78375588],
        [0.31781526, 0.39399133]]])

In [56]:
#Random Integer Values
np.random.randint(10, size = (3,3))

array([[8, 3, 7],
       [4, 2, 4],
       [6, 1, 9]])

In [ ]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Repeate an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr , 3 , axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Question [[1 ,1 ,1 , 1, 1],
          [1 ,0 ,0 ,0 , 1],
          [1 ,0 ,9 ,0 , 1],
          [1 ,0 ,0 ,0 , 1],
          [1 ,1 ,1 , 1, 1]]

In [91]:
Arr = np.ones((5 , 5))

In [99]:
Arr[1:4 , 1:4] = [0]

In [100]:
Arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
Arr[2,2] = 9

In [102]:
Arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Be carfull when

In [112]:
B = np.array([1,2,3])
C = B.copy()
C[2] = 100
print(B)

[1 2 3]


Mathematics

In [126]:
D = np.array([10,20,30])
print(D)

[10 20 30]


In [115]:
D + 2

array([12, 22, 32])

In [116]:
D - 2

array([ 8, 18, 28])

In [117]:
D / 2

array([ 5., 10., 15.])

In [118]:
D * 2

array([20, 40, 60])

In [119]:
E = np.array([4,4,4])

In [120]:
D + E

array([14, 24, 34])

In [121]:
D ** 2

array([100, 400, 900])

In [127]:
#Take the sign of all values
np.sin(D)

array([-0.54402111,  0.91294525, -0.98803162])

Linear Algebra

In [134]:
n = np.full((3,3) ,2)
print(n)

m = np.full((3,2) , 5)
print(m)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[5 5]
 [5 5]
 [5 5]]


In [ ]:
#To multiplay
np.matmul(n,m)

array([[30, 30],
       [30, 30],
       [30, 30]])

In [ ]:
#TO find determinant
o = np.identity(3)
np.linalg.det(o)

np.float64(1.0)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

Statistics with Numpy

In [141]:
stat = np.array([[1,2,3] , [4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
np.min(stat , axis= 1)

array([1, 4])

In [144]:
np.max(stat , axis=1)

array([3, 6])

In [148]:
np.sum(stat,axis=1)

array([ 6, 15])

Reorganising array

In [154]:
before = np.array([[1,2,3,4] , [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [156]:
#after = before.reshape((4,2))
after = before.reshape((4,1,2))
print(after)

[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]


In [158]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
#Horizontal Stack
h1 = np.zeros((2,4))
h2 = np.ones((2,2))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [166]:
np.hstack((h1,h2))

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

Miscellaneous

Load data from File

In [171]:
data = np.genfromtxt('data.txt' , delimiter=',')
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [182]:
data = data.astype('int32')
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean Masking And Advanceed Indexing

In [173]:
data > 3

array([[False,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True, False, False, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True],
       [False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False,  True,  True,  True, False,  True,  True]])

In [175]:
data[data > 10]

array([ 13.,  21.,  11., 196.,  75.,  34.,  42.,  12.,  33., 766.,  75.,
        55.,  11.,  12.,  22.,  33.,  11., 999.,  11.,  78.,  76.,  88.])

In [178]:
#Can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,5]]

array([2, 4, 6])

In [183]:
np.any(data > 50 , axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [185]:
(~((data > 50) & (data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])